scoreboard objectives add knockback dummy knockback
scoreboard objectives add jump dummy jump
scoreboard objectives add overheadblock dummy overheadblock
scoreboard objectives add feetblock dummy feetblock
scoreboard objectives add eyeblock dummy eyeblock
scoreboard objectives add jumpblock dummy jumpblock
scoreboard objectives add simple dummy simple
scoreboard objectives add fence dummy fence
scoreboard objectives add slide dummy slide
scoreboard objectives add sidewallleftup dummy sidewallleftup
scoreboard objectives add sidewallleftdown dummy sidewallleftdown
scoreboard objectives add sidewallrightup dummy sidewallrightup
scoreboard objectives add sidewallrightdown dummy sidewallrightdown
scoreboard objectives add sidewallleft dummy sidewallleft
scoreboard objectives add sidewallright dummy sidewallright
scoreboard objectives add sidewall dummy sidewall
scoreboard objectives add wallrunning dummy wallrunning
scoreboard objectives add wallrunpass dummy wallrunpass
scoreboard objectives add lasttickypos dummy lasttickypos